name: gregg-grid
favicon: null
layout_spectrum: 0.5669548576697707
typography_spectrum: 0.9170559141784906
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4716119235381484
  lightness: 0.8645102952141315
  saturation: 0.17568255751393735
  rhythmicContrast: 0.34005913184955716
purpose: []
